import designLogo from "../assets/images/icons/design-file.png";
import documentsLogo from "../assets/images/icons/documents-file.png";
import musicLogo from "../assets/images/icons/music-file.png";
import imagesLogo from "../assets/images/icons/images-file.png";
import quickAccess1 from "../assets/images/quickAccess/image-1.png";
import quickAccess2 from "../assets/images/quickAccess/image-2.png";
import quickAccess3 from "../assets/images/quickAccess/image-3.png";
import recentlyUpload1 from "../assets/images/recentlyUpload/image-2.png";
import recentlyUpload2 from "../assets/images/recentlyUpload/image-3.png";
import recentlyUpload3 from "../assets/images/recentlyUpload/image-4.png";
import recentlyUpload4 from "../assets/images/recentlyUpload/image-5.png";
import bottomBanner from "../assets/images/bottomBanner.png";
import faviconImage from "../assets/images/logo.png";

const design = document.getElementById("top-card-design");
const documents = document.getElementById("top-card-documents");
const music = document.getElementById("top-card-music");
const images = document.getElementById("top-card-images");
const quickAccessImage1 = document.getElementById("quick-access-img-1");
const quickAccessImage2 = document.getElementById("quick-access-img-2");
const quickAccessImage3 = document.getElementById("quick-access-img-3");
const recentlyUploadImage1 = document.getElementById("ru-1");
const recentlyUploadImage2 = document.getElementById("ru-2");
const recentlyUploadImage3 = document.getElementById("ru-3");
const recentlyUploadImage4 = document.getElementById("ru-4");
const recentlyUploadImage5 = document.getElementById("ru-5");
const bottomBannerImage = document.getElementById("bottom-banner");
const favicon = document.getElementById("title-logo");

design.setAttribute("src", designLogo);
documents.setAttribute("src", documentsLogo);
music.setAttribute("src", musicLogo);
images.setAttribute("src", musicLogo);
quickAccessImage1.setAttribute("src", quickAccess1);
quickAccessImage2.setAttribute("src", quickAccess2);
quickAccessImage3.setAttribute("src", quickAccess3);
recentlyUploadImage1.setAttribute("src", recentlyUpload1);
recentlyUploadImage2.setAttribute("src", recentlyUpload2);
recentlyUploadImage3.setAttribute("src", recentlyUpload3);
recentlyUploadImage4.setAttribute("src", recentlyUpload4);
recentlyUploadImage5.setAttribute("src", recentlyUpload1);
bottomBannerImage.setAttribute("src", bottomBanner);
favicon.setAttribute("href", faviconImage);
